# Generated by Django 3.1.4 on 2020-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
