# Generated by Django 3.1.4 on 2020-12-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0002_article_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='read_articles',
        ),
        migrations.CreateModel(
            name='ReadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muffin.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muffin.user')),
            ],
        ),
    ]
