# Generated by Django 3.1.4 on 2020-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0004_auto_20201229_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_feeds',
            field=models.ManyToManyField(to='muffin.Feed'),
        ),
    ]
