# Generated by Django 3.1.4 on 2021-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0006_auto_20210101_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_words',
            field=models.IntegerField(null=True),
        ),
    ]
