# Generated by Django 3.1.4 on 2021-01-08 17:55

from django.db import migrations, models


def update_existing(apps, schema_editor):
    from muffin.controllers import get_favicon_url
    from muffin.models import Feed

    FakeFeed = apps.get_model("muffin", "feed")
    for feed in FakeFeed.objects.all():
        real_feed = Feed(url=feed.url)
        source_url = real_feed.rss_data["channel"]["link"]
        feed.favicon_url = get_favicon_url(source_url)
        feed.save(update_fields=["favicon_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("muffin", "0007_auto_20210108_0807"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="favicon_url",
            field=models.URLField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(update_existing, reverse_code=migrations.RunPython.noop),
    ]
