# Generated by Django 3.1.4 on 2021-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0008_feed_favicon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
