# Generated by Django 3.1.4 on 2021-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muffin', '0005_user_followed_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_feeds',
            field=models.ManyToManyField(related_name='followers', to='muffin.Feed'),
        ),
    ]
